### PR TITLE
Update prompt-file.py

### PR DESCRIPTION
**Pull request by venkatkamparaju**

### CODE REVIEW

**Comment by moseya4325** [comment]
Why removed the zero index in the print statements?

**Comment by venkatkamparaju** [comment]
Thanks for the review Mos. I see only the first prediction value printing. My understanding is that, I see this program to explore the predictions for a given prompt. I tried to print all the responses of the prompt.

Thanks again.

**Comment by moseya4325** [comment]
Very good. Got it. good job.

**Comment by venkatkamparaju** [comment]
yes

**Pull request merged**
